### ISSUE TITLE
software release

### ISSUE THREAD

**Issue by rogerkuou** [TUDelftGeodesy/stmtools#40]
- [x] Tests
   - [x] already there
   - [x] lint test
- [x] Documentation ---> @rogerkuou 
    - [x] add logo 
    - [x] mkdoc rendering
    - [x] Function Examples
    - [x] Add tutorial
    - [x] Add contributing or developerguide
- [x] GitHub actions ---> @SarahAlidoost 
    - [x] Add a `pyproject.toml` file
            - Update doc link
            - Update change log link 
            - Update author names
    - [x] Build package and documentation when push and pull request
    - [x] Doc deploy when release
    - [x] Test using sonarcloud!
           - set up sonar (one-time)
           - setup sonar and github secrets token 
           - add sonar properties file
- [ ] Update citations and author names
    - [ ] cff
    - [ ] zenodo json
- [x] README  ---> @SarahAlidoost 
    - [x] Update description
    - [x] Installation example
    - [x] Checklist Badge:  [![OpenSSF Best Practices](https://www.bestpractices.dev/projects/7980/badge)](https://www.bestpractices.dev/projects/7980)
    - [x] Other badges:
        - [x] Sonarcloud
- [x] Publish to PyPI
    - [x] GH workflow

**Comment by fnattino** [comment]
See https://github.com/MotionbyLearning/sarxarray/issues/33

**Comment by rogerkuou** [comment]
Good idea! I will try it in #51
