### ISSUE TITLE
Querying temporal attributes to an STM

### ISSUE THREAD

**Issue by rogerkuou** [TUDelftGeodesy/stmtools#63]
Add a `enrich_from_stm()` function to enrich a STM with spatial temporal data (another STM)

This function should take another xr.Dataset with the same space/time dimension and CRS.

The enrichment should support block-wise operation as `enrich_from_polygon` .

An example usage adapted from the [Documentation example](https://tudelftgeodesy.github.io/stmtools/notebooks/demo_stm/)

```python
import xarray as xr

# Read temperature data to query
ds_temperature = xr.read_nc('temperature.nc')

# Read existing stm data
path_stm = Path('./stm.zarr')
stmat = xr.open_zarr(path_stm)

# Enrich
stmat.stm.enrich_from_stm(ds_temperature , space_label=('lat', 'lon'), time_label ='time')

``` 

Work example: enrich the [STM (Zarr) over Amsterdam](https://dataplatform.knmi.nl/dataset/preview/tg1-5) in [demo](https://tudelftgeodesy.github.io/stmtools/notebooks/demo_stm/) with KNMI daily mean temperature.

**Comment by rogerkuou** [comment]
Might be useful to check:
https://github.com/Deltares/xugrid
https://xesmf.readthedocs.io/en/latest/

**Comment by rogerkuou** [comment]
Hi @SarahAlidoost, Freek shared the saptio-temporal data they would like to work with in #64. These data are more relevant than the KNMI dataset. I will copy his message here:

> This is the link:
> 
> https://www.daggegevens.knmi.nl/klimatologie/uurgegevens
> 
> The idea would be to insert meteo data into the STM of the data (e.g. temperature, pressure) closest to the SAR satellite acquisition. (But maybe also: the sum of rainfall in the last 3 days, etc).
> 
> Furthermore, I attached:
> - an example data file (just 1000 lines) [knmi_stn280_example_file.txt](https://github.com/TUDelftGeodesy/stmtools/files/14569633/knmi_stn280_example_file.txt)
> - two old Matlab scripts, handling the data. [importMeteodata_knmi.zip](https://github.com/TUDelftGeodesy/stmtools/files/14570327/importMeteodata_knmi.zip)
> [get_meteo.zip](https://github.com/TUDelftGeodesy/stmtools/files/14569640/get_meteo.zip)
> - .csv file with KNMI station locations [knmistations.csv](https://github.com/TUDelftGeodesy/stmtools/files/14570346/knmistations.csv) (see also https://github.com/MotionbyLearning/sandbox/tree/develop_vector_processing for an example implementation using these station locations made earlier (in the 'step 3' script).

**Comment by SarahAlidoost** [comment]
this can be useful https://docs.xarray.dev/en/stable/generated/xarray.Dataset.interp_like.html#xarray-dataset-interp-like 
example https://docs.xarray.dev/en/stable/generated/xarray.DataArray.interp_like.html#xarray.DataArray.interp_like
